# Generated by Django 3.2.7 on 2021-12-06 16:55

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='performance',
            field=picklefield.fields.PickledObjectField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='projectstatistics',
            name='stats',
            field=picklefield.fields.PickledObjectField(blank=True, editable=False, null=True),
        ),
    ]
