# Generated by Django 3.2.7 on 2021-12-25 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_auto_20211206_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='model_name',
            field=models.CharField(choices=[('log_reg', 'Logistic regression'), ('svm', 'SVM'), ('kernel_svm', 'Kernel SVM'), ('svm_prob', 'Probabilistic SVM'), ('rfc', 'Random forest classifier'), ('mlp', 'Multilayer perceptron'), ('rnn', 'RNN'), ('lstm', 'LSTM'), ('gru', 'GRU'), ('bert', 'BERT')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='vectorizer_name',
            field=models.CharField(blank=True, choices=[('count', 'Count'), ('tf_idf', 'TF-IDF'), ('vec_avg', 'Average word vector'), ('emb_matrx', 'Embedding matrix')], max_length=30, null=True),
        ),
    ]
