# Generated by Django 3.2.7 on 2022-01-03 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_auto_20211225_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='al_method',
            field=models.CharField(choices=[('least_conf', 'Least confident'), ('margin', 'Margin'), ('entropy', 'Entropy'), ('entropy_density', 'Entropy + Informative density'), ('multilab_uncert', 'Multi-label uncertainty')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='model_name',
            field=models.CharField(choices=[('log_reg', 'Logistic regression'), ('linear_svm', 'Linear SVM'), ('kernel_svm', 'Kernel SVM'), ('rfc', 'Random forest classifier'), ('mlp', 'Multilayer perceptron'), ('rnn', 'RNN'), ('lstm', 'LSTM'), ('gru', 'GRU'), ('bert', 'BERT')], max_length=30, null=True),
        ),
    ]
