# Generated by Django 3.2.7 on 2022-01-13 11:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('server', '0004_auto_20220103_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='member',
            field=models.ManyToManyField(related_name='member_in_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
