# Generated by Django 3.2.7 on 2022-02-11 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_userlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlog',
            name='type',
            field=models.CharField(max_length=64),
        ),
    ]
