# Generated by Django 3.2.7 on 2022-02-12 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_alter_userlog_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlog',
            name='metadata',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
