# Generated by Django 3.2.7 on 2022-03-18 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0010_alter_project_al_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kexdocument',
            name='document_ptr',
        ),
        migrations.RemoveField(
            model_name='kexproject',
            name='project_ptr',
        ),
        migrations.AlterUniqueTogether(
            name='seq2seqannotation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='seq2seqannotation',
            name='document',
        ),
        migrations.RemoveField(
            model_name='seq2seqannotation',
            name='user',
        ),
        migrations.RemoveField(
            model_name='seq2seqdocument',
            name='document_ptr',
        ),
        migrations.RemoveField(
            model_name='seq2seqproject',
            name='project_ptr',
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('Classification', 'Classification'), ('Sequence Labeling', 'Sequence Labeling'), ('Keyphrase Extraction', 'Keyphrase Extraction'), ('Named Entity Recognition', 'Named Entity Recognition')], max_length=30),
        ),
        migrations.DeleteModel(
            name='KexAnnotation',
        ),
        migrations.DeleteModel(
            name='KexDocument',
        ),
        migrations.DeleteModel(
            name='KexProject',
        ),
        migrations.DeleteModel(
            name='Seq2seqAnnotation',
        ),
        migrations.DeleteModel(
            name='Seq2seqDocument',
        ),
        migrations.DeleteModel(
            name='Seq2seqProject',
        ),
    ]
