# Generated by Django 3.2.7 on 2022-03-22 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0011_auto_20220318_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='indexing',
            field=models.TextField(blank=True, null=True),
        ),
    ]
