# Generated by Django 3.2.7 on 2022-05-25 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0016_project_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
