# Generated by Django 3.2.7 on 2022-06-06 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('server', '0017_alter_project_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOptions',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='options', serialize=False, to='auth.user')),
                ('use_color', models.BooleanField(default=False)),
            ],
        ),
    ]
